apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
    version: {{ .Values.image.tag }}
    environment: {{ .Values.environment }}
    AccountableTeam: my-project
    tags.datadoghq.com/env: {{ .Values.environment }}
    tags.datadoghq.com/service:  {{ .Values.app.name }}
    tags.datadoghq.com/version: {{ .Values.image.tag }}

spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        version: {{ .Values.image.tag }}
        environment: {{ .Values.environment }}
        AccountableTeam: my-project
        tags.datadoghq.com/env: {{ .Values.environment }}
        tags.datadoghq.com/service:  {{ .Values.app.name }}
        tags.datadoghq.com/version: {{ .Values.image.tag }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.container.image }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        env:
        - name: kafkaBrokerList
          value: "{{ .Values.kafka.endpoint }}.{{ .Values.app.namespace }}.svc.cluster.local"
        - name: kafkaBrokerPort
          value: "{{ .Values.kafka.port }}"          
        - name: serviceName
          value: "{{ .Values.service.name }}"
        - name: port
          value: "{{ .Values.service.port }}"                
        - name: ShortHash
          value: "{{ .Values.vcs.commit }}"
        - name: buildNumber
          value: "1.0.{{ .Values.BUILD_NUMBER }}"
        - name: postgresContactPoint
          value: "{{ .Values.postgres.contact.point }}.{{ .Values.app.namespace }}.svc.cluster.local"
        - name: postgresContactPointPort
          value: "{{ .Values.postgres.contact.port }}"
        - name: postgresDatabase
          value: "{{ .Values.postgres.database }}"
        - name: postgresSchema
          value: "{{ .Values.postgres.schema }}"     
        - name: postgresDbUserName
          value: "{{ .Values.postgres.dbusername }}"
        - name: postgresDbPassword
          valueFrom:
            secretKeyRef:
              name: cmp-passwords
              key: "PostgresDataPassword-{{ .Values.environment }}"
        - name: workingEnv
          value: "{{ .Values.variables.workingEnv }}"
        - name: dbRetryInterval
          value: "{{ .Values.variables.dbRetryInterval }}"
        - name: brokersAvailabilityCheckInterval
          value: "{{ .Values.variables.brokersAvailabilityCheckInterval }}"
        - name: kafkaK8Broker
          value: "{{ .Values.variables.kafkaK8Broker }}"
        - name: connectInternalToK8Kafka
          value: "{{ .Values.variables.connectInternalToK8Kafka }}"
        - name: kafkaGroupId
          value: "{{ .Values.variables.kafkaGroupId }}"
        {{ if (ne "prod" .Values.variables.workingEnv) }}
        volumeMounts:
        - name: kafka-secrets
          mountPath: "/etc/kafka-secrets"
        {{ end }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
        livenessProbe:
            httpGet:
              path: /api/v1/status
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 90
            timeoutSeconds: 30
        readinessProbe:
            httpGet:
              path: /api/v1/status
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 90
            timeoutSeconds: 30
        resources:
          requests:
            cpu: "10m"
            memory: "100Mi"
          limits:
            cpu: "300m"
            memory: "500Mi"
      imagePullSecrets:
      - name: regcred
      {{ if (ne "prod" .Values.variables.workingEnv) }}
      volumes:
        - name: kafka-secrets
          secret:
              items:
              - key: ca.pem
                path: kafka/ca.pem
                mode: 0777
              - key: kafkak8.crt
                path: kafka/kafkak8.crt
                mode: 0777
              - key: kafkak8.key
                path: kafka/kafkak8.key
                mode: 0777
              secretName: my-project-kafka-{{ .Values.variables.workingEnv }}-secret
      {{ end }}

