apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.port }}
