apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
    environment: {{ .Values.environment }}
    monitoring: {{ .Values.app.name }}-sm-{{ .Values.environment }}
    version: {{ .Values.image.tag }}
    AccountableTeam: my-project
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: http
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.app.name }}

